[package]
name = "advent2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5"
reformation = "0.5"
itertools = "0.10"
pathfinding = "3"
bitvec = "0.22"
nalgebra = "0.29"

